### ISSUE TITLE
evalution results of PASCAL-S contain NaN. (results from BASNet,AFNet)

### ISSUE THREAD

**Issue by StormArcher** [lartpang/SODEvalToolkit#5]
可能由于图片中无显著物体，导致求Recall时分母为0，得到Nan，求Recall时将分母加上1e-16，防止分母为0.（这个方法是过了无法解决）

**Comment by lartpang** [comment]
1. 首先请明确，这份代码是按照真值的名字来查找对应的预测图，所以如果使用的真值图片要多于预测结果的话，那么就会报错，会提示有些图片找不到。我这里测试的时候，AFNet使用的只有845张真值。
2. 经过我的测试，发现问题就是出在这5张图上，建议删掉。

**Comment by lartpang** [comment]
我所使用的pascal-s的图片名字列表：
[image845_list.txt](https://github.com/lartpang/SODEvalToolkit/files/4487305/image845_list.txt)
