### ISSUE TITLE
恭喜中了20的c会，能否提供下用于画曲线的这几个数据集的saliency map?

### ISSUE THREAD

**Issue by StormArcher** [lartpang/SODEvalToolkit#6]
MLMSNet,PAGE,HRS, C2SNet, EGNet-R, CPD-R(这些是你们论文里面曲线的算法)
BASNet,SCRN

**Comment by lartpang** [comment]
* 大部分数据可以从这里找到，我估计他们应该未来也会继续更新。https://github.com/wenguanwang/SODsurvey
* CPD-R：https://github.com/wuzhe71/CPD
* EGNet：https://github.com/JXingZhao/EGNet
* SCRN：https://github.com/wuzhe71/SCRN

似乎EGNet的文件名字和真值不同，我会上传一份EGNet的DUT-OMRON的预测图。
如有需求请留言。
